pipeline {
	agent any

	parameters {
		string(name: 'OCI_COMPUTE_HOST')
		string(name: 'DB_HOST',)
        password(name: 'DB_PASSWORD')
        string(name: 'DB_PORT')
        string(name: 'KAKAO_CLIENT_ID')
        string(name: 'NAVER_CLIENT_ID')
        password(name: 'NAVER_CLIENT_SECRET')
        string(name: 'GOOGLE_CLIENT_ID')
        password(name: 'GOOGLE_SECRET')
        password(name: 'JWT_SECRET')
        password(name: 'KEYSTORE_B64')
        password(name: 'KEYSTORE_PASSWORD')
    }

	stages {
		stage('Checkout') {
			steps {
				git url: 'https://github.com/wheon06/yeoun.git', branch: 'main'
            }
		}

		stage('Setup Keystore') {
			steps {
				sh '''
					echo "$KEYSTORE_B64" | base64 -d > backend/src/main/resources/keystore.p12
				'''
			}
		}

        stage('Build with Gradle') {
			steps {
				sh '''
                    cd backend
                    chmod +x ./gradlew
                    ./gradlew clean build
                '''
            }
        }

        stage('Docker Build') {
			steps {
				sh '''
                    docker build -t yeoun-back:latest ./backend
                '''
            }
        }

		stage('Deploy') {
			steps {
				sh '''
                    docker rm -f yeoun-back || true

                    docker run -d \
                    --name yeoun-back \
                    -p 7070:8080 \
                    -e DB_HOST=$DB_HOST \
                    -e DB_PORT=$DB_PORT \
                    -e DB_PASSWORD=$DB_PASSWORD \
                    -e JWT_SECRET=$JWT_SECRET \
                    -e OCI_COMPUTE_HOST=$OCI_COMPUTE_HOST \
                    -e KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
                    -e GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
                    -e GOOGLE_SECRET=$GOOGLE_SECRET \
                    -e NAVER_CLIENT_ID=$NAVER_CLIENT_ID \
                    -e NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET \
                    -e KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID \
                    -e SPRING_PROFILES_ACTIVE=prod \
                    yeoun-back:latest
                '''
            }
        }
	}
}