pipeline {
	agent any

	parameters {
		string(name: 'OCI_COMPUTE_HOST', description: 'OCI Public IP')
		string(name: 'DB_HOST', description: 'Database Host')
        password(name: 'DB_PASSWORD', description: 'Database Password')
        string(name: 'DB_PORT', description: 'Database Port', defaultValue: '3306')
        string(name: 'KAKAO_CLIENT_ID', description: 'Kakao Client ID')
        string(name: 'NAVER_CLIENT_ID', description: 'Naver Client ID')
        password(name: 'NAVER_CLIENT_SECRET', description: 'Naver Client Secret')
        string(name: 'GOOGLE_CLIENT_ID', description: 'Google Client ID')
        password(name: 'GOOGLE_SECRET', description: 'Google Client Secret')
        password(name: 'JWT_SECRET', description: 'JWT Secret Key')
        password(name: 'KEYSTORE_B64', description: 'Base64-encoded keystore.p12')
        password(name: 'KEYSTORE_PASSWORD', description: 'Keystore Password')
    }

	stages {
		stage('Checkout') {
			steps {
				git url: 'https://github.com/wheon06/yeoun.git', branch: 'main'
            }
		}

		stage('Setup Keystore') {
			steps {
				sh '''
					echo "$KEYSTORE_B64" | base64 -d > ./backend/src/main/resources/keystore.p12
				'''
			}
		}

		stage('Docker Build') {
			steps {
				sh 'docker build -t yeoun-back:latest ./backend'
            }
		}

		stage('Deploy') {
			steps {
				sh '''
                    docker rm -f yeoun-back || true
                    docker run -d \
                    --name yeoun-back \
                    -p 7070:8080 \
                    -e DB_HOST=$DB_HOST \
                    -e DB_PORT=$DB_PORT \
                    -e DB_PASSWORD=$DB_PASSWORD \
                    -e JWT_SECRET=$JWT_SECRET \
                    -e OCI_COMPUTE_HOST=$OCI_COMPUTE_HOST \
                    -e KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
                    -e GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
                    -e GOOGLE_SECRET=$GOOGLE_SECRET \
                    -e NAVER_CLIENT_ID=$NAVER_CLIENT_ID \
                    -e NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET \
                    -e KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID \
                    -e SPRING_PROFILES_ACTIVE=prod \
                    yeoun-back:latest
                '''
            }
        }
	}
}