kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: https://${OCI_COMPUTE_HOST}:8080/public/auth/login/kakao

naver:
  client_id: ${NAVER_CLIENT_ID}
  redirect_uri: https://${OCI_COMPUTE_HOST}:8080/public/auth/login/naver
  client_secret: ${NAVER_CLIENT_SECRET}

google:
  client_id: ${GOOGLE_CLIENT_ID}
  client_secret: ${GOOGLE_SECRET}
  redirect_uri: https://${OCI_COMPUTE_HOST}:8080/public/auth/login/google

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/yeoun
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-time: 3600000
  refresh-token-expiration-time: 604800000

server:
  tomcat:
    connection-timeout=-1:

sse:
  connection_time:
    3600000 # 60L * 1000 * 60 #1 시간
    # 10000 # 1000 * 10 = test 환경 10초

scheduler:
  # cron: "0 * * * * *" # 1분 간격으로 실행
  cron: 0 0 2 * * ?  # 매일 오전 2시에 실행됨
  # user_history_delete_second: 30 # 60 * 2  test 환경 2분
  user_history_delete_second: 18144000 # 한달 (30일)
  every-day: "0 0 0 * * *"

user:
  default-question-count:
    1
  # user_history_delete_second: 18144000 # 한달 (30일)