name: React / Spring CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-22.04

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: 도커 빌드 셋업
        uses: docker/setup-buildx-action@v2

      - name: 도커 허브에 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 도커 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/yeoun-front:latest
            ${{ secrets.DOCKER_USERNAME }}/yeoun-front:${{ github.sha }}

      - name: 서버에 SSH 접속 및 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.OCI_COMPUTE_HOST }}
          username: ${{ secrets.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            echo "도커 허브로부터 이미지 Pull"
            docker pull ${{ secrets.DOCKER_USERNAME }}/yeoun-front:latest
            
            echo "기존 컨테이너 중지 및 삭제"
            docker stop yeoun-front || true
            docker rm yeoun-front || true
            
            echo "새 컨테이너 시작"
            docker run -d --name yeoun-front -p 80:80 ${{ secrets.DOCKER_USERNAME }}/yeoun-front:latest

  backend:
    runs-on: ubuntu-22.04

    steps:
    - name: 레포지토리 체크아웃
      uses: actions/checkout@v3

    - name: 도커 빌드 셋업
      uses: docker/setup-buildx-action@v2

    - name: 도커 허브에 로그인
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: keystore.p12 인증서 주입
      run: |
        echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > ./backend/src/main/resources/keystore.p12

    - name: 백엔드 이미지 빌드 및 푸시
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/yeoun-back:latest
          ${{ secrets.DOCKER_USERNAME }}/yeoun-back:${{ github.sha }}

    - name: 서버에 SSH 접속 및 배포
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.OCI_COMPUTE_HOST }}
        username: ${{ secrets.OCI_SSH_USER }}
        key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
        port: ${{ secrets.OCI_SSH_PORT }}
        script: |
          echo "도커 허브로부터 이미지 Pull"
          docker pull ${{ secrets.DOCKER_USERNAME }}/yeoun-back:latest
              
          echo "기존 컨테이너 중지 및 삭제"
          docker stop yeoun-back || true
          docker rm yeoun-back || true
            
          echo "새 컨테이너 시작"
          docker run -d \
            --name yeoun-back \
            -p 8080:8080 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e OCI_COMPUTE_HOST=${{ secrets.OCI_COMPUTE_HOST }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
            -e NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
            -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
            -e SPRING_PROFILES_ACTIVE=prod \
            ${{ secrets.DOCKER_USERNAME }}/yeoun-back:latest
