name: CI

on:
  pull_request:
    types: [opend, labeled, synchronize, reopened]

jobs:
  spring-test:
    if: contains(github.event.pull_request.labels.*.name, 'BE')
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend

      steps:
        - uses: actions/checkout@v3

        - name: JDK 설정
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'temurin'

        - name: 스프링부트 테스트코드 실행
          run: ./gradlew test