name: Deploy to Oracle Compute

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./backend/src/main/resources/application.yml

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: wheon06/yeoun-backend:latest